
name: ci

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  pull:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: